### ISSUE TITLE
Text HighLight

### ISSUE THREAD

**Issue by xmaxmex** [limbo666/LiveLogs#1]
Hi, cool program... :)

You can implement a text highlight with diferent colors ?

Thanks in advance!

**Comment by limbo666** [comment]
Thanks.
Do you mean that you need to select the color on seacrh or you need to highlight multiple search terms with different colors?

**Comment by limbo666** [comment]
Text colors added on version [#1.0.0.4](https://github.com/limbo666/LiveLogs/releases/tag/1.0.0.4)
